# Generated by Django 4.2.3 on 2023-07-26 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_shipping_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='total_price',
        ),
    ]
