# Generated by Django 4.2.3 on 2023-07-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='session_id',
            field=models.TextField(),
        ),
    ]
