# Generated by Django 4.2.3 on 2023-07-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_cart_shipping_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_product',
            field=models.ManyToManyField(blank=True, null=True, to='store.cart'),
        ),
    ]
